# Generated by Django 5.0.3 on 2024-04-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_mgmt', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userStatus',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved'), ('Pending', 'Pending')], default='Pending', max_length=12),
        ),
    ]
