# Generated by Django 5.0.3 on 2024-04-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_mgmt', '0003_users_userstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='userStatus',
        ),
    ]
