# Generated by Django 5.0.4 on 2024-04-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
