# Generated by Django 5.0.3 on 2024-04-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalItems', models.IntegerField()),
                ('availableItems', models.IntegerField()),
                ('onLoanItems', models.IntegerField()),
                ('inRepairItems', models.IntegerField()),
                ('decommissionedItems', models.IntegerField()),
            ],
        ),
    ]
