# Generated by Django 5.0.3 on 2024-04-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('userEmail', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=100)),
                ('userPassword', models.CharField(max_length=100)),
                ('userType', models.CharField(choices=[('STU', 'Student'), ('STA', 'Staff')], default='STU', max_length=3)),
            ],
        ),
    ]
