# Generated by Django 5.0.3 on 2024-04-16 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='generatedOn',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
