# Generated by Django 4.0 on 2024-04-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_equipment_comments_equip_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='available_items',
            new_name='instock_items',
        ),
        migrations.AlterField(
            model_name='equip_item',
            name='status',
            field=models.CharField(choices=[('on_loan', 'On loan'), ('repairing', 'Repairing'), ('decommisioned', 'Dicommisioned'), ('available', 'Available')], default='available', max_length=20),
        ),
    ]
