# Generated by Django 4.0 on 2024-04-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_available_items_equipment_instock_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip_item',
            name='item_quantity',
        ),
        migrations.AlterField(
            model_name='equip_item',
            name='item_CPU',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equip_item',
            name='item_GPU',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equip_item',
            name='item_RAM',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equip_item',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equip_item',
            name='status',
            field=models.CharField(choices=[('decommisioned', 'Dicommisioned'), ('on_loan', 'On loan'), ('available', 'Available'), ('repairing', 'Repairing')], default='available', max_length=20),
        ),
    ]
