# Generated by Django 5.0.3 on 2024-04-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_equip_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip_item',
            name='status',
            field=models.CharField(choices=[('repairing', 'Repairing'), ('on_loan', 'On loan'), ('available', 'Available'), ('decommisioned', 'Dicommisioned')], default='available', max_length=20),
        ),
    ]
