# Generated by Django 4.0 on 2024-04-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_equipment_status_alter_equip_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='onsite_only',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='equip_item',
            name='status',
            field=models.CharField(choices=[('on_loan', 'On loan'), ('decommisioned', 'Dicommisioned'), ('available', 'Available'), ('repairing', 'Repairing')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('In-Repair', 'In-Repair'), ('Decommisioned', 'Decommisioned'), ('On-Loan', 'On-Loan'), ('Available', 'Available')], default='Available', max_length=20),
        ),
    ]
