# Generated by Django 5.0.3 on 2024-04-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(max_length=99999)),
            ],
        ),
    ]
