# Generated by Django 4.0 on 2024-04-21 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_equipment_available_items_alter_equipment_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Equip_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('serial_number', models.IntegerField()),
                ('item_type', models.CharField(max_length=100)),
                ('item_quantity', models.IntegerField()),
                ('item_CPU', models.IntegerField(blank=True)),
                ('item_GPU', models.IntegerField(blank=True)),
                ('item_RAM', models.IntegerField(blank=True)),
                ('status', models.CharField(choices=[('decommisioned', 'Dicommisioned'), ('available', 'Available'), ('repairing', 'Repairing'), ('on_loan', 'On loan')], default='available', max_length=20)),
                ('equipmentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.equipment')),
            ],
        ),
    ]
