# Generated by Django 5.0.3 on 2024-04-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_equip_item_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip_item',
            name='status',
            field=models.CharField(choices=[('on_loan', 'On loan'), ('decommisioned', 'Dicommisioned'), ('available', 'Available'), ('repairing', 'Repairing')], default='available', max_length=20),
        ),
    ]
